apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: springboot-app-prod
  namespace: ${OPENSHIFT_PROJECT_NAME}
spec:
  replicas: 1
  selector:
    app: springboot-app-prod
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: springboot-app-prod
    spec:
      containers:
      - name: springboot-app-prod
        image: ${OPENSHIFT_REGISTRY_URL}/${OPENSHIFT_PROJECT_NAME}/${DOCKER_IMAGE_NAME}:latest
        ports:
        - containerPort: 8080
        env:
        - name: CORS_ALLOWED_ORIGINS
          value: ${CORS_ALLOWED_ORIGINS}
        - name: CORS_ALLOWED_METHODS
          value: ${CORS_ALLOWED_METHODS}
        - name: SPRING_DATASOURCE_URL
          value: ${SPRING_DATASOURCE_URL}
        - name: SPRING_DATASOURCE_USERNAME
          value: ${SPRING_DATASOURCE_USERNAME}
        - name: SPRING_DATASOURCE_PASSWORD
          value: ${SPRING_DATASOURCE_PASSWORD}
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
